---
abstract: 'dbicdump your Mojo app schema'
author:
  - 'Alister West <alister@alisterwest.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Command-generate-dbicdump
provides:
  Mojolicious::Command::generate::dbicdump:
    file: lib/Mojolicious/Command/generate/dbicdump.pm
    version: v0.1.1
recommends:
  Pod::Readme: 0
  Pod::Select: 0
requires:
  DBIx::Class::Schema::Loader: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: v0.1.1
